{"name": "test_existent_user_new_pass", "status": "passed", "description": "Function responsible for the unsucessful register in the application with an existant username\n    \n    Arguments:\n        None\n\n    Returns:\n        1 if the test is successful (App's response is the intended), 0 otherwise\n    \n    Raises:\n        Exception if the login page could not be loaded\n    ", "start": 1699311154277, "stop": 1699311159370, "uuid": "dc26a3ed-92d7-4c36-aa35-9fd5f1b82013", "historyId": "604d8d2d1e8a61dd51a9e48d27f0d5f6", "testCaseId": "604d8d2d1e8a61dd51a9e48d27f0d5f6", "fullName": "REQ1.test_1_2_Register_Existent_User_New_Pass#test_existent_user_new_pass", "labels": [{"name": "severity", "value": "critical"}, {"name": "story", "value": "login com username existente na aplicação"}, {"name": "feature", "value": "REQ1 - Pagina de Login e Registo"}, {"name": "parentSuite", "value": "REQ1"}, {"name": "suite", "value": "test_1_2_Register_Existent_User_New_Pass"}, {"name": "host", "value": "linux-VirtualBox"}, {"name": "thread", "value": "18164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "REQ1.test_1_2_Register_Existent_User_New_Pass"}]}